spring:
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      # create / create-drop / update / validate / none
      ddl-auto: none
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/board-db
    username: board-master
    password: board-postgres-password
  security:
    user.name: board-admin
    user.password: board-admin-password
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 1234

jwt:
  secret-key: secret
  expiredMillis: 600


logging:
  level:
    root: info
#    org.hibernate.type : TRACE
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG
#    org.springframework.orm.jpa: DEBUG
#    org.springframework.transaction: DEBUG
